apiVersion: batch/v1
kind: Job
metadata:
  name: notifications
  namespace: kcli-infra
  labels:
    app: kcli
spec:
  backoffLimit: {{ 20 if sno else 12 }}
  template:
   spec:
{% if not sno %}
    nodeSelector:
      kubernetes.io/hostname: {{ cluster }}-ctlplane-0.{{ domain }}
{% endif %}
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    serviceAccountName: autoapprover
    restartPolicy: OnFailure
    initContainers:
    - name: wait-for-cluster-version
      image: {{ registry }}/karmab/kubectl:multi
      command:
      - "/bin/sh"
      - "-c"
      - |
        #!/bin/sh
        until [ "$CLUSTER_VERSION" == "Completed" ] ; do
          CLUSTER_VERSION=$(kubectl get clusterversion version -o jsonpath='{.status.history[0].state}')
          sleep 30
        done
        kubectl get clusterversion > /shared/results.txt
        kubectl get nodes >> /shared/results.txt
      volumeMounts:
      - mountPath: /shared
        name: shared
    containers:
    - name: launch-notify-cmds
      securityContext:
        privileged: true
      image: {{ registry }}/karmab/curl:multi
      command:
      - "/bin/sh"
      - "-c"
      - |
        #!/bin/sh
{% if mailcontent != None %}
{% set mailcontent = mailcontent.split('\n') %}
{% for line in mailcontent %}
        echo "{{ line }}" >> /var/tmp/mail.txt
{% endfor %}
{% endif %}
{% for cmd in cmds %}
        {{ cmd }}
{% endfor %}
        rm -f /etc/kubernetes/kubeconfig.{{ cluster }}
      volumeMounts:
      - name: shared
        mountPath: /shared
      - name: conf-dir
        mountPath: "/etc/kubernetes"
    volumes:
    - name: shared
      emptyDir: {}
    - name: conf-dir
      hostPath:
        path: "/etc/kubernetes"
